### ISSUE TITLE
Problems with gulp init

### ISSUE THREAD

**Issue by wayne-dooley-nih** [uswds/uswds-tutorial#5]
Hi all -- I'm attempting to complete the tutorial, and I'm running into a snag at part two, step 7. When I attempt the 'npx gulp init', I receive the following errors:
 
```
 ~/uswds-tutorial  dooleywm $  npx gulp init
[16:12:26] Using gulpfile ~/uswds-tutorial/gulpfile.js
[16:12:26] Starting 'init'...
[16:12:26] Starting 'theme'...
Copying USWDS theme files to ./_theme
[16:12:26] 'theme' errored after 858 μs
[16:12:26] TypeError: paths.src.theme.replaceAll is not a function
    at theme (/Users/dooleywm/uswds-tutorial/node_modules/@uswds/compile/gulpfile.js:87:43)
    at bound (domain.js:416:15)
    at runBound (domain.js:427:12)
    at asyncRunner (/Users/dooleywm/uswds-tutorial/node_modules/async-done/index.js:55:18)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
[16:12:26] 'init' errored after 2.8 ms
```
Here's the contents of my gulpfile.js:
 
```
const uswds = require('@uswds/compile');

uswds.paths.dist.theme = './_theme';

exports.init = uswds.init;
exports.compile = uswds.compile;
exports.watch = uswds.watch;
```

Appreciate your help!

**Comment by kristenmyers** [comment]
I am running into the same problem.

**Comment by wayne-dooley** [comment]
@kristenmyers -- Yep, that was it! I upgraded node version, and all is working well. Thanks for the help!

**Comment by mejiaj** [comment]
Thank you for sharing @kristenmyers!

**Comment by fpigeonjr** [comment]
completed the tutorial using node16 and didn't run into any issues.
btw, you can run `nvm use` at the root of any project that has a `.nvmrc` and know that it will be set to the correct version.

**Comment by mejiaj** [comment]
@thisisdano this should be safe to close.

**Comment by ryparker** [comment]
Closing this resolved setup report. The discussion confirms the tutorial worked after switching to its required Node version, and recommends closure: https://github.com/uswds/uswds-tutorial/issues/5#issuecomment-1065702119 and https://github.com/uswds/uswds-tutorial/issues/5#issuecomment-1342937365. This does not certify the current tutorial's other build or dependency issues.
