### ISSUE TITLE
Problem Installing

### ISSUE THREAD

**Issue by JeffOnWire** [uswds/uswds-tutorial#6]
Got to step 2, _run npm install_ and it had some issues:

```
$ npm install
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!

> uswds-tutorial@ postinstall C:\Users\*****\Documents\Unnamed Site 2\uswds-tutorial
> npm run jekyll:install


> uswds-tutorial@ jekyll:install C:\Users\*****\Documents\Unnamed Site 2\uswds-tutorial
> gem install bundler && bundle install

'gem' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! uswds-tutorial@ jekyll:install: `gem install bundler && bundle install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the uswds-tutorial@ jekyll:install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\*****\AppData\Roaming\npm-cache\_logs\2022-02-02T23_33_40_513Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! uswds-tutorial@ postinstall: `npm run jekyll:install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the uswds-tutorial@ postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\*****\AppData\Roaming\npm-cache\_logs\2022-02-02T23_33_40_635Z-debug.log
```

Here's the log

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install'
1 verbose cli ]
2 info using npm@6.14.13
3 info using node@v14.17.0
4 verbose npm-session 403003ef27246cc0
5 silly install runPreinstallTopLevelLifecycles
6 silly preinstall uswds-tutorial@
7 info lifecycle uswds-tutorial@~preinstall: uswds-tutorial@
8 silly install loadCurrentTree
9 silly install readLocalPackageData
10 timing stage:loadCurrentTree Completed in 10ms
11 silly install loadIdealTree
12 silly install cloneCurrentTreeToIdealTree
13 timing stage:loadIdealTree:cloneCurrentTree Completed in 0ms
14 silly install loadShrinkwrap
15 warn read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
16 timing stage:loadIdealTree:loadShrinkwrap Completed in 365ms
17 silly install loadAllDepsIntoIdealTree
18 timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 544ms
19 timing stage:loadIdealTree Completed in 1157ms
20 silly currentTree uswds-tutorial@
21 silly idealTree uswds-tutorial@
21 silly idealTree `-- snyk@1.821.0
22 silly install generateActionsToTake
23 timing stage:generateActionsToTake Completed in 25ms
24 silly diffTrees action count 1
25 silly diffTrees add snyk@1.821.0
26 silly decomposeActions action count 8
27 silly decomposeActions fetch snyk@1.821.0
28 silly decomposeActions extract snyk@1.821.0
29 silly decomposeActions preinstall snyk@1.821.0
30 silly decomposeActions build snyk@1.821.0
31 silly decomposeActions install snyk@1.821.0
32 silly decomposeActions postinstall snyk@1.821.0
33 silly decomposeActions finalize snyk@1.821.0
34 silly decomposeActions refresh-package-json snyk@1.821.0
35 silly install executeActions
36 silly doSerial global-install 8
37 verbose correctMkdir C:\Users\*****\AppData\Roaming\npm-cache\_locks correctMkdir not in flight; initializing
38 verbose makeCacheDir UID & GID are irrelevant on win32
39 verbose lock using C:\Users\*****\AppData\Roaming\npm-cache\_locks\staging-b00f11812fe83826.lock for C:\Users\*****\Documents\Unnamed Site 2\uswds-tutorial\node_modules\.staging
40 silly doParallel extract 1
41 silly extract snyk@1.821.0
42 silly tarball trying snyk@1.821.0 by hash: sha512-ZKFwIrdhBf2kOxDUUpf1gKiOehu4B1nu16pXZ9H6bRp4t7QIdVVtjsqGAy0pmWqug8+1uroMb/SsGFmumRwVsw==
43 silly tarball no local data for snyk@1.821.0. Extracting by manifest.
44 timing audit submit Completed in 301ms
45 http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/audits/quick 301ms
46 timing audit body Completed in 0ms
47 http fetch GET 200 https://registry.npmjs.org/snyk/-/snyk-1.821.0.tgz 7328ms
48 silly extract snyk@1.821.0 extracted to C:\Users\*****\Documents\Unnamed Site 2\uswds-tutorial\node_modules\.staging\snyk-2a333cbc (7546ms)
49 timing action:extract Completed in 7548ms
50 silly doReverseSerial unbuild 8
51 silly doSerial remove 8
52 silly doSerial move 8
53 silly doSerial finalize 8
54 silly finalize C:\Users\*****\Documents\Unnamed Site 2\uswds-tutorial\node_modules\snyk
55 timing action:finalize Completed in 5ms
56 silly doParallel refresh-package-json 1
57 silly refresh-package-json C:\Users\*****\Documents\Unnamed Site 2\uswds-tutorial\node_modules\snyk
58 timing action:refresh-package-json Completed in 17ms
59 silly doParallel preinstall 1
60 silly preinstall snyk@1.821.0
61 info lifecycle snyk@1.821.0~preinstall: snyk@1.821.0
62 timing action:preinstall Completed in 0ms
63 silly doSerial build 8
64 silly build snyk@1.821.0
65 info linkStuff snyk@1.821.0
66 silly linkStuff snyk@1.821.0 has C:\Users\*****\Documents\Unnamed Site 2\uswds-tutorial\node_modules as its parent node_modules
67 verbose linkBins [
67 verbose linkBins   { snyk: 'bin/snyk' },
67 verbose linkBins   'C:\\Users\\*****\\Documents\\Unnamed Site 2\\uswds-tutorial\\node_modules\\.bin',
67 verbose linkBins   false
67 verbose linkBins ]
68 timing action:build Completed in 7ms
69 silly doSerial global-link 8
70 silly doParallel update-linked 0
71 silly doSerial install 8
72 silly install snyk@1.821.0
73 info lifecycle snyk@1.821.0~install: snyk@1.821.0
74 timing action:install Completed in 1ms
75 silly doSerial postinstall 8
76 silly postinstall snyk@1.821.0
77 info lifecycle snyk@1.821.0~postinstall: snyk@1.821.0
78 timing action:postinstall Completed in 0ms
79 verbose unlock done using C:\Users\*****\AppData\Roaming\npm-cache\_locks\staging-b00f11812fe83826.lock for C:\Users\*****\Documents\Unnamed Site 2\uswds-tutorial\node_modules\.staging
80 timing stage:executeActions Completed in 7617ms
81 timing stage:rollbackFailedOptional Completed in 0ms
82 silly install runPostinstallTopLevelLifecycles
83 silly build uswds-tutorial@
84 info linkStuff uswds-tutorial@
85 silly linkStuff uswds-tutorial@ has C:\Users\*****\Documents\Unnamed Site 2 as its parent node_modules
86 silly install uswds-tutorial@
87 info lifecycle uswds-tutorial@~install: uswds-tutorial@
88 silly postinstall uswds-tutorial@
89 info lifecycle uswds-tutorial@~postinstall: uswds-tutorial@
90 verbose lifecycle uswds-tutorial@~postinstall: unsafe-perm in lifecycle true
91 verbose lifecycle uswds-tutorial@~postinstall: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\*****\Documents\Unnamed Site 2\uswds-tutorial\node_modules\.bin;P:\bin;C:\Users\*****\AppData\Local\Programs\Git\mingw64\bin;C:\Users\*****\AppData\Local\Programs\Git\usr\local\bin;C:\Users\*****\AppData\Local\Programs\Git\usr\bin;C:\Users\*****\AppData\Local\Programs\Git\usr\bin;C:\Users\*****\AppData\Local\Programs\Git\mingw64\bin;C:\Users\*****\AppData\Local\Programs\Git\usr\bin;P:\bin;C:\Program Files (x86)\Micro Focus\Reflection;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\WINDOWS\System32\OpenSSH;C:\Program Files\1E\Client\Extensibility\NomadBranch;C:\Program Files (x86)\HID Global\ActivClient;C:\Program Files\HID Global\ActivClient;C:\Program Files\SafeNet\Authentication\SAC\x64;C:\Program Files\SafeNet\Authentication\SAC\x32;C:\Program Files (x86)\Webex\Plugins;C:\Program Files\Microsoft SQL Server\130\Tools\Binn;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn;C:\Program Files\nodejs;C:\ProgramData\chocolatey\bin;C:\Program Files\PolicyPak;C:\Program Files (x86)\Microsoft SQL Server\150\DTS\Binn;C:\Program Files\Azure Data Studio\bin;C:\Program Files\PowerShell\7;C:\Program Files\dotnet;C:\Users\*****\AppData\Local\Microsoft\WindowsApps;C:\Users\*****\AppData\Roaming\npm;C:\Users\*****\AppData\Local\Programs\Git\cmd;C:\Users\*****\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\*****\AppData\Local\Programs\Fiddler;%USERPROFILE%\AppData\Local\Microsoft\WindowsApps;C:\Users\*****\AppData\Local\Programs\Git\usr\bin\vendor_perl;C:\Users\*****\AppData\Local\Programs\Git\usr\bin\core_perl
92 verbose lifecycle uswds-tutorial@~postinstall: CWD: C:\Users\*****\Documents\Unnamed Site 2\uswds-tutorial
93 silly lifecycle uswds-tutorial@~postinstall: Args: [ '/d /s /c', 'npm run jekyll:install' ]
94 silly lifecycle uswds-tutorial@~postinstall: Returned: code: 1  signal: null
95 info lifecycle uswds-tutorial@~postinstall: Failed to exec postinstall script
96 verbose stack Error: uswds-tutorial@ postinstall: `npm run jekyll:install`
96 verbose stack Exit status 1
96 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
96 verbose stack     at EventEmitter.emit (events.js:376:20)
96 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
96 verbose stack     at ChildProcess.emit (events.js:376:20)
96 verbose stack     at maybeClose (internal/child_process.js:1055:16)
96 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
97 verbose pkgid uswds-tutorial@
98 verbose cwd C:\Users\*****\Documents\Unnamed Site 2\uswds-tutorial
99 verbose Windows_NT 10.0.19044
100 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
101 verbose node v14.17.0
102 verbose npm  v6.14.13
103 error code ELIFECYCLE
104 error errno 1
105 error uswds-tutorial@ postinstall: `npm run jekyll:install`
105 error Exit status 1
106 error Failed at the uswds-tutorial@ postinstall script.
106 error This is probably not a problem with npm. There is likely additional logging output above.
107 verbose exit [ 1, true ]

```

**Comment by mejiaj** [comment]
Sorry to hear you're having trouble @JeffOnWire. Could you provide a little more information so we can help troubleshoot?

- What version of Ruby do you have installed on your windows machine?
- Do you have ruby available in your `PATH`? This makes it work in the command line.

**Comment by JeffOnWire** [comment]
Thanks for your help!

I think I've got my Ruby issue sorted. I'm getting certificate validation errors, several that all look like this:

ERROR:  SSL verification error at depth 2: self signed certificate in certificate chain (19)
ERROR:  Root certificate is not trusted (/DC=gov/DC=va/CN=VA-Internal-S2-RCA1-v1)

**Comment by mejiaj** [comment]
@JeffOnWire since your original ruby issue is solved I'm going to close this issue. Please create a new issue for any new bugs.
