### ISSUE TITLE
USWDS-Tutorial - Bug: Problem writing Eleventy

### ISSUE THREAD

**Issue by fritzwf** [uswds/uswds-tutorial#65]
### Describe the bug

[11ty] Problem writing Eleventy templates:
[11ty] Output conflict: multiple input files are writing to `./_site/extend.html`. Use distinct `permalink` values to resolve this conflict.
[11ty]   1. ./uswds-tutorial/pages/02-extending/index.html
[11ty]   2. ./pages/02-extending/index.html (via DuplicatePermalinkOutputError)
[11ty]
[11ty] Original error stack trace: (Repeated output has been truncated…)
[11ty]     at TemplateMap.checkForDuplicatePermalinks (file:///C:/Dev/USWDS/uswds-tutorial/node_modules/@11ty/eleventy/src/TemplateMap.js:733:10)
[11ty]     at TemplateMap.cache (file:///C:/Dev/USWDS/uswds-tutorial/node_modules/@11ty/eleventy/src/TemplateMap.js:456:8)
[11ty]     at async TemplateWriter._createTemplateMap (file:///C:/Dev/USWDS/uswds-tutorial/node_modules/@11ty/eleventy/src/TemplateWriter.js:356:3)
[11ty]     at async TemplateWriter.generateTemplates (file:///C:/Dev/USWDS/uswds-tutorial/node_modules/@11ty/eleventy/src/TemplateWriter.js:386:3)
[11ty]     at async TemplateWriter.write (file:///C:/Dev/USWDS/uswds-tutorial/node_modules/@11ty/eleventy/src/TemplateWriter.js:434:21)
[11ty]     at async Eleventy.executeBuild (file:///C:/Dev/USWDS/uswds-tutorial/node_modules/@11ty/eleventy/src/Eleventy.js:1345:19)
[11ty]     at async Eleventy.watch (file:///C:/Dev/USWDS/uswds-tutorial/node_modules/@11ty/eleventy/src/Eleventy.js:1155:3)
[11ty] Copied 2 Wrote 0 files in 0.73 seconds (v3.0.0)****

### Steps to reproduce the bug

When trying to use the **uswds-tutorial**, I pulled it down and ran the *npm i*, and when I ran **npm start*, it came back with this error:

[11ty] Problem writing Eleventy templates:

**More below...**

### Expected Behavior

The **npm start** should have run the app.

### Related code

**Below is the error:**

[11ty] Problem writing Eleventy templates:
[11ty] Output conflict: multiple input files are writing to `./_site/extend.html`. Use distinct `permalink` values to resolve this conflict.
[11ty]   1. ./uswds-tutorial/pages/02-extending/index.html
[11ty]   2. ./pages/02-extending/index.html (via DuplicatePermalinkOutputError)
[11ty]
[11ty] Original error stack trace: (Repeated output has been truncated…)
[11ty]     at TemplateMap.checkForDuplicatePermalinks (file:///C:/Dev/USWDS/uswds-tutorial/node_modules/@11ty/eleventy/src/TemplateMap.js:733:10)
[11ty]     at TemplateMap.cache (file:///C:/Dev/USWDS/uswds-tutorial/node_modules/@11ty/eleventy/src/TemplateMap.js:456:8)
[11ty]     at async TemplateWriter._createTemplateMap (file:///C:/Dev/USWDS/uswds-tutorial/node_modules/@11ty/eleventy/src/TemplateWriter.js:356:3)
[11ty]     at async TemplateWriter.generateTemplates (file:///C:/Dev/USWDS/uswds-tutorial/node_modules/@11ty/eleventy/src/TemplateWriter.js:386:3)
[11ty]     at async TemplateWriter.write (file:///C:/Dev/USWDS/uswds-tutorial/node_modules/@11ty/eleventy/src/TemplateWriter.js:434:21)
[11ty]     at async Eleventy.executeBuild (file:///C:/Dev/USWDS/uswds-tutorial/node_modules/@11ty/eleventy/src/Eleventy.js:1345:19)
[11ty]     at async Eleventy.watch (file:///C:/Dev/USWDS/uswds-tutorial/node_modules/@11ty/eleventy/src/Eleventy.js:1155:3)
[11ty] Copied 2 Wrote 0 files in 0.73 seconds (v3.0.0)

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://designsystem.digital.gov/about/community/#community-conduct).
- [x] I checked the [current issues](https://github.com/uswds/uswds-tutorial/issues) for duplicate bug reports.

**Comment by fritzwf** [comment]
I found the issue.  On the page 02-extending in the index.html, the text in the top of the file, should be like this:

****
